### ISSUE TITLE
add promise support

### ISSUE THREAD

**Issue by gitawego** [PlayNetwork/mongoose-middleware#26]
thanks for this great plugin. but I'd suggest you add Promise support. that could be nice :)

**Comment by brozeph** [comment]
@gitawego thanks for the suggestion! I'll keep this open for tracking as we do the implementation...

**Comment by brozeph** [comment]
@gitawego - thank you for your suggestion!

In addition to the support that Mongoose provides for Promises (<http://mongoosejs.com/docs/promises.html>), we have implemented [Promise support](https://github.com/PlayNetwork/mongoose-middleware#promise-support) on the `page` method in this module as well.

```javascript
var options = {
  start : 0,
  count : 500
};

KittehModel
  .find()
  .page(options)
  .then((kittehs) => {
    console.log('we haz kittehs!');
    console.log(kittehs);
  })
  .catch(console.error);
```
