### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by rdiazroman** [PlayNetwork/mongoose-middleware#30]
Hello,

I'm having this issue to initialise mongoose-middleware, when I try to start my server:

`    /Users/rubendiazroman/projects/mean/node_modules/mongoose-middleware/lib/field.js:4
    	mongoose.Query.prototype.field = function (options) {
    	                            ^
    
    TypeError: Cannot read property 'prototype' of undefined
        at module.exports (/Users/rubendiazroman/projects/mean/node_modules/mongoose-middleware/lib/field.js:4:16)
        at Object.module.exports.initialize (/Users/rubendiazroman/projects/mean/node_modules/mongoose-middleware/lib/index.js:10:20)
        at Object.<anonymous> (/Users/rubendiazroman/projects/mean/config/lib/app.js:13:32)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)`

I have used this piece of code in my server.js:

`var mongoose = require('./mongoose');

require('mongoose-middleware').initialize(mongoose);`

Any help please?
Thanks!
Ruben

**Comment by PN-mruiz** [comment]
@rdiazroman 
which version of mongoose are you using?

also, i noticed there's a ./ where you're requiring mongoose, is that intentional?

**Comment by rdiazroman** [comment]
"mongoose": "~4.2.3",

yep, the "./" is OK. Mongoose was working before. 
Thanks!

**Comment by PN-mruiz** [comment]
i'm a little concerned about the ./ because that suggests you're referencing a file in your project, rather than then named package. so you might try removing that to see if the issue clears up (if you have a file named mongoose in your project, you might make sure a mongoose object is returned out of it when it's ```require```d).

mongoose-middleware tries to modify the prototype of the Query object that hangs off mongoose, so it might be helpful to do something like this...

```
var mongoose = require('./mongoose');
for (var x in mongoose) {
    console.log(x);
}
```

just to see the keys. there should be one called ```Query```.

**Comment by brozeph** [comment]
In Mongoose v4.2.3, the Query property does exist: <https://github.com/Automattic/mongoose/blob/2df330b8a3e3215908f6b41c3ddc1ed6818be9a2/lib/index.js#L606>

Also, our tests pass when physically running against v4.2.3 - so something else must be occurring here.

Can you try removing the `./` before `mongoose` in your require statement and let us know the results?

**Comment by rdiazroman** [comment]
You are right.
I'm using meanjs.org framework. It creates a single file for mongoose configuration.
Initialising mongoose-middleware in that file solved the issue.

https://snag.gy/fAidSO.jpg

Many thanks!
