### ISSUE TITLE
I cannot search russian(cyrilic) keywords

### ISSUE THREAD

**Issue by canercak** [PlayNetwork/mongoose-middleware#33]
Hi,
When I search(filter) for latin keywords I get relavant results but I cannot filter cyrlic keywords and get the below error. Is there a workaround for this?

> GET /api/preproviders?user=undefined&role=undefined&filter=+&order=oblast.ru&sort=desc+&per_page=10&page=0 - - ms - -
> { sort: { desc: 'oblast.ru' }, start: 0, count: '10' }
> { sort: { desc: 'oblast.ru' },
>   start: 0,
>   count: '10',
>   filters: { keyword: { fields: [Object], term: 'мирабо ' } } }
> TypeError: Cannot read property 'forEach' of null
>     at getKeywordRegex (/Users/apple/Desktop/dev/posluga/node_modules/mongoose-middleware/lib/keyword.js:16:10)
>     at Query.keyword (/Users/apple/Desktop/dev/posluga/node_modules/mongoose-middleware/lib/keyword.js:51:19)
>     at index (/Users/apple/Desktop/dev/posluga/server/api/preprovider/preprovider.controller.js:113:37)
>     at Layer.handle [as handle_request] (/Users/apple/Desktop/dev/posluga/node_modules/express/lib/router/layer.js:95:5)
>     at next (/Users/apple/Desktop/dev/posluga/node_modules/express/lib/router/route.js:131:13)
> 

This is my code:

```
export function index(req, res) {
    var filteredQuery = {
        'createdby': req.query.user
    }
    if (req.query.role === 'admin') {
        filteredQuery = {};
    }
    var options = {
        sort: {},
        start: req.query.page * req.query.per_page,
        count: req.query.per_page
    };
    if (req.query.filter !== ' ') {
        options['filters'] = {
            keyword: {
                fields: ['company', 'website', 'oblast.ru', 'rayon.ru'],
                term: req.query.filter
            }
        };
    }
    var param = req.query.sort;
    options['sort'] = {
        [param.trim()]: req.query.order
    }
    console.log(options)
    Preprovider.find(filteredQuery).keyword(options).order(options).page(options, function(err, preproviders) {
        if (err) {
            return handleError(res, err);
        }
        return res.status(200).json(preproviders);
    });
}
```

**Comment by brozeph** [comment]
Hi @canercak, thank you for submitting this issue with the details you have provided!

After looking closely, there is an area in the mongoose-middleware module that requires adjustment. The exception occurs within the keyword module - a Regex match is applied to the value of the `term` that is passed into the keyword filter method. In this case, based on your example above, the value is a space (` `) and there are no matches. The code attempts to iterate over a null result. I'll fix and deploy in `v0.3.0`.

**Comment by brozeph** [comment]
Hi @canercak - if you upgrade to `v0.3.0` of the `mongoose-middleware` module, this issue should now be resolved.

**Comment by canercak** [comment]
ok. Thank you.
